Pipelines:
 QCcontrol
 assemble
 evaluete
 align
 user_define
Tools:
 jellyfish:
  bin: /bubo/home/h23/vezzi/assembly_pipeline/tools/jellyfish-1.1.11/bin/jellyfish
  options: ""
 fastqc:
  bin: /bubo/sw/apps/bioinfo/fastqc/0.10.1/kalkyl/fastqc
  options: [--threads,  "8" ,  --outdir,  fastqc]
 trimmomatic:
  bin: /home/vezzi/assembly_pipeline/tools/Trimmomatic-0.30/trimmomatic-0.30.jar
  options: ["PE", "-phred33", "-threads", "8"]
 masurca:
  bin: /bubo/home/h23/vezzi/assembly_pipeline/tools/MaSuRCA-2.0.4/
  options: 
 abyss:
  bin: /bubo/sw/apps/bioinfo/abyss/1.3.5/kalkyl/bin/
  options: ["k=54", "np=8"]
 abyss_mergePairs:
  bin: /bubo/sw/apps/bioinfo/abyss/1.3.5/kalkyl/bin/abyss-mergepairs
  options: ["-m 20", "-1 230", "-2 230"]
 soapdenovo:
  bin: /bubo/home/h23/vezzi/assembly_pipeline/tools/SOAPdenovo2-src-r240/SOAPdenovo-63mer
  options: [""]
 spades:
  bin: /home/vezzi/assembly_pipeline/tools/SPAdes-2.5.1-Linux/bin/spades.py
  options: ["--careful", "-t 8"]
 cabog:
  bin: /home/vezzi/assembly_pipeline/tools/wgs-7.0/Linux-amd64/bin/
  options: [""]
 FRC:
  bin: /home/vezzi/assembly_pipeline/tools/FRC_align/src/FRC
  options: ""
 CEGMA:
  bin: /sw/apps/bioinfo/cegma/2.4.010312/kalkyl/bin/cegma
  options: ""
 bwa:
  bin: /sw/apps/bioinfo/bwa/0.7.4/kalkyl/bin/bwa
  options: ""
 picard:
  bin: /proj/a2010002/nobackup/sw/mf/bioinfo-tools/picard-tools/1.95/
  options: ""
 samtools:
  bin: /sw/apps/bioinfo/samtools/0.1.19/kalkyl/bin/samtools
  options: ""
 qaTools:
  bin: /home/vezzi/assembly_pipeline/tools/qaTools/
  options: ""
