Pipelines:
 QCcontrol
 assemble
 evaluete
 align
 user_define
Tools:
 jellyfish:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/jellyfish-1.1.11/bin/jellyfish
  options: ""
 fastqc:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/FastQC/fastqc
  options: [--threads,  "20" ,  --outdir,  fastqc]
 trimmomatic:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/Trimmomatic-0.32/trimmomatic-0.30.jar
  options: ["PE", "-phred33", "-threads", "20"]
 abyss:
  bin: /usr/local/abyss-1.3.6/bin/abyss-pe
  options: ["k=54", "np=20"]
 abyss_mergePairs:
  bin: /usr/local/abyss-1.3.6/bin/abyss-mergepairs
  options: ["-m 20", "-1 230", "-2 230"]
 soapdenovo:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/SOAPdenovo2/SOAPdenovo-63mer
  options: [""]
 allpaths:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/allpathslg-47856/
  options: [""]
 bwa:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/bwa-0.7.5a/bwa
  options: ""
 picard:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/picard-tools-1.103/
  options: ""
 samtools:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/samtools-0.1.18/samtools
  options: ""
 qaTools:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/qaTools/
  options: ""
